### ISSUE TITLE
Minis aren't scaled if base is scaled.

### ISSUE THREAD

**Issue by brajm008** [LordAshes/TaleSpire-CustomMiniPlugin#1]
So if minis are not using a base of 1x1 size, Minis still spawn in at 1x1 size even though the base size is different. 
Would be nice for the mini to check initial scale and scale dependent on the base to match.

**Comment by LordAshes** [comment]
Confirmed. Mini scale when the base size is changed AFTER transformation
but the initial transformation always comes in at the regular size. I will
have a look to see how difficult it would be to adjust on initial
transformation.

Best Regards,

Lord Ashes

**Comment by LordAshes** [comment]
This issue has been resolved in version 4.4.0. Transformation content now scaled to the base size when loaded.
