### ISSUE TITLE
when I swap the mini for a custom, the old model does not go away.

### ISSUE THREAD

**Issue by Roxfall** [LordAshes/TaleSpire-CustomMiniPlugin#2]
is it because the old model is "unique"?

![image](https://user-images.githubusercontent.com/30673911/126053505-04216bd5-2169-43b7-9f41-9eace7e0c65e.png)

**Comment by Roxfall** [comment]
Also noticed that the new model does not react to surprised or wiggle animation, but reacts to twirl. Looks like it is parented to the wrong bone. Twirl makes it lift, but it does not make it spin.

The old visible model still does all the animations. 

Tried to transform a non-unique model, same problems. 

When I hide the model, the base and the old model vanish, but the new model is still visible.

Also, the new model cannot be selected by clicking on it. In the picture above I can click on the sword of the old model, but not on the axe of the new model

**Comment by Roxfall** [comment]
In case it is relevant, these are the mods running 
![image](https://user-images.githubusercontent.com/30673911/126053734-99d9849c-8c1e-4e47-9a79-1deb3ccc7305.png)
Tried to disable ThunderManPlugin, it failed to even load the new model. No dice.

**Comment by Roxfall** [comment]
This is in 5.0.0 btw.

**Comment by Roxfall** [comment]
Update: bug does not exist in 4.9.2

**Comment by Roxfall** [comment]
Correction: it does not exist in 4.9.2 only when it is installed without ThunderManPlugin. Installing ThunderManPLugin 1.2.2 on top of 4.9.2 results in this bug as well. Tried 5.0.0 without ThunderManPlugin, also results in the same bug.

**Comment by LordAshes** [comment]
Video Link: https://youtu.be/KjvJceR08jI

Lord Ashes

**Comment by Roxfall** [comment]
Aha. So why isn't Ctrl-M in the radial menu? I am following this guide and it has been quite confusing. https://old.reddit.com/r/talespire/comments/of0qgf/stepbystep_guide_to_import_your_hero_forge_minis/?

Looks like a legacy system already?

**Comment by LordAshes** [comment]
<Grin> I get asked that a lot. My philosophy is not to pollute the radial
menu with items that you will not use frequently. Most minis will get
transformed once and then remain with the transformation for the rest of
the game. Effects on the other hand can change frequently depending on what
the minis are casting or what it is representing. So, CMP adds a radial
icon for Effect but not for Mini Transformation. If you have a mini that
needs to transform frequently (e.g. Wild Shape for Druid or Polymorph
spell) then there is a Polymorph plugin which allows you to add up to 10
mini transformations to the radial menu.

Best Regards,

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
That Reddit post isn't mine, so I apologize for the inaccuracy but it was
not my doing.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
A posted a correct in the Reddit but it will end up getting
buried among other comments.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
